# Generated by Django 3.1.14 on 2022-05-25 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=12)),
                ('team', models.CharField(max_length=20)),
                ('organization_impacted_by_incident', models.CharField(max_length=20)),
                ('incident_discovery_method', models.TextField()),
                ('affiliation_to_org', models.CharField(max_length=30)),
                ('user_incident_reported_by', models.CharField(max_length=20)),
                ('employee_email', models.EmailField(max_length=254)),
                ('customer_email', models.EmailField(max_length=254)),
                ('prevention', models.TextField()),
                ('additional_notes', models.TextField()),
                ('date_incident_reported', models.DateField(auto_now_add=True)),
                ('date_incident_occured', models.DateField()),
            ],
        ),
    ]
