# Generated by Django 3.1.14 on 2022-05-28 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_happened', models.CharField(choices=[('Inadvertent Data Exposure', 'Inadvertant Data Exposure'), ('Security Misconfiguration', 'Security Misconfiguration'), ('Product Vulnerability', 'Product Vulnerability'), ('Vendor Incident', 'Vendor Incident')], max_length=40)),
                ('customer_id', models.CharField(max_length=15)),
                ('customer_email', models.EmailField(max_length=254)),
                ('when_did_it_happen', models.DateField(auto_now_add=True)),
                ('how_was_it_discovered', models.CharField(max_length=100)),
                ('additional_notes', models.TextField()),
                ('when_was_the_incident_submitted', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
