# Generated by Django 3.1.14 on 2022-05-25 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='phone_number',
        ),
    ]
