# Generated by Django 3.1.14 on 2022-05-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='how_could_we_have_prevented_this',
            field=models.TextField(default=0.010330578512396695),
            preserve_default=False,
        ),
    ]
