# Generated by Django 3.1.14 on 2022-05-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_incident_how_could_we_have_prevented_this'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='how_was_it_discovered',
            field=models.TextField(),
        ),
    ]
