# Generated by Django 3.1.14 on 2022-05-28 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_auto_20220528_0107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='when_was_the_incident_submitted',
            new_name='data_of_incident',
        ),
    ]
