# Generated by Django 3.1.14 on 2022-05-30 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidents', '0004_auto_20220528_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default=0.008264462809917356, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incident',
            name='author',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
